workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            DEVELOPMENT_TEAM=ARU75H5867 \  # Hardcoded your Team ID here
            -allowProvisioningUpdates
    publishing:
      scripts:
        - name: Export IPA
          script: |
            xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/Runner.ipa \
            -allowProvisioningUpdates
    artifacts:
      - $CM_BUILD_DIR/Runner.ipa
