workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Update Ruby to 2.7 (Log Ruby version)
        script: |
          brew install rbenv
          rbenv init
          rbenv install 2.7.4
          rbenv global 2.7.4
          ruby -v
          echo "Ruby updated and version is:"
          ruby -v

      - name: Install CocoaPods using Homebrew (with logging)
        script: |
          brew install cocoapods || echo "CocoaPods installation failed!"

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          echo "Running pod install in $(pwd)"
          pod install --verbose || { echo "pod install failed!"; exit 1; }

      - name: Verify .xcworkspace file exists
        script: |
          cd ios
          WORKSPACE_PATH=$(pwd)/Runner.xcworkspace
          echo "Checking for .xcworkspace at path: $WORKSPACE_PATH"
          if [ ! -d $WORKSPACE_PATH ]; then
            echo "ERROR: Runner.xcworkspace not found at $WORKSPACE_PATH!"
            exit 1
          else
            echo "SUCCESS: Runner.xcworkspace found at $WORKSPACE_PATH."
          fi

      - name: Build iOS
        script: |
          cd ios
          WORKSPACE_PATH=$(pwd)/Runner.xcworkspace
          echo "Building using workspace at $WORKSPACE_PATH"
          xcodebuil
