workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          echo "Running pod install in $(pwd)"
          pod install --verbose || { echo "pod install failed!"; exit 1; }
