workflows:
  ios-workflow:
    name: iOS Build Workflow
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update || pod install
          
      - name: Verify Workspace and Directory
        script: |
          echo "Current directory:"
          pwd
          echo "Listing ios directory:"
          ls -la ios
          if [ -d "ios/Runner.xcworkspace" ]; then
            echo "Runner.xcworkspace exists."
          else
            echo "ERROR: Runner.xcworkspace not found!"
            exit 1
          fi

      - name: Build iOS
        script: |
          WORKSPACE_PATH=$(pwd)/ios/Runner.xcworkspace
          echo "Building using workspace at $WORKSPACE_PATH"
          xcodebuild -workspace $WORKSPACE_PATH -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Runner.xcarchive DEVELOPMENT_TEAM=ARU75H5867 -allowProvisioningUpdates || { echo "xcodebuild failed!"; exit 1; }

      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Runner.xcarchive -exportPath $CM_BUILD_DIR -exportOptionsPlist ios/ExportOptions.plist

    artifacts:
      - $CM_BUILD_DIR/**/*.ipa
      - $CM_BUILD_DIR/**/*.xcarchive
