workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      vars:
        DEVELOPMENT_TEAM: "ARU75H5867"  # Your team ID
        CERTIFICATE_PASSWORD: "595ABYbc"  # Your .p12 certificate password
    scripts:
      - name: Install dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build the app
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath $CM_BUILD_DIR/Runner.xcarchive \
          DEVELOPMENT_TEAM=$DEVELOPMENT_TEAM \
          -allowProvisioningUpdates
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
          -archivePath $CM_BUILD_DIR/Runner.xcarchive \
          -exportOptionsPlist ios/ExportOptions.plist \
          -exportPath $CM_BUILD_DIR/Runner.ipa \
          -allowProvisioningUpdates
    artifacts:
      - $CM_BUILD_DIR/Runner.ipa
      - $CM_BUILD_DIR/Runner.xcarchive
