workflows:
  ios-workflow:
    name: iOS Build Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $HOME/output/Runner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/output/Runner.xcarchive -exportPath $HOME/output -exportOptionsPlist ./ios/ExportOptions.plist
