workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Update Ruby to 2.7
        script: |
          brew install rbenv
          rbenv init
          rbenv install 2.7.4
          rbenv global 2.7.4
          ruby -v
      - name: Install Homebrew (if missing)
        script: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install CocoaPods using Homebrew
        script: |
          brew install cocoapods
      - name: Install CocoaPods dependencies
        script: |
          cd charlie/ios
          pod install --verbose || exit 1
      - name: List directory contents after pod install (debug)
        script: |
          ls -la charlie/ios
      - name: Verify .xcworkspace file exists (correct path)
        script: |
          if [ ! -f charlie/ios/Runner.xcworkspace ]; then
            echo "Runner.xcworkspace not found in charlie/ios directory!"
            exit 1
          else
            echo "Runner.xcworkspace found in charlie/ios directory."
          fi
      - name: Build iOS
        script: |
          cd charlie/ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $HOME/build/Runner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/build/Runner.xcarchive -exportOptionsPlist charlie/ios/Runner/ExportOptions.plist -exportPath $HOME/build
    artifacts:
      - build/Runner.ipa
