workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $CM_BUILD_DIR/Runner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/Runner.xcarchive -exportPath $CM_BUILD_DIR -exportOptionsPlist ios/ExportOptions.plist
      - name: Publish IPA to TestFlight
        script: |
          # You can publish to TestFlight or any other platform
          echo "Publishing to TestFlight"

    artifacts:
      - $CM_BUILD_DIR/**/*.ipa
      - $CM_BUILD_DIR/Runner.xcarchive
