workflows:
  ios-workflow:
    name: iOS Build Workflow
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
    scripts:
      - name: Install Homebrew (if missing)
        script: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Install CocoaPods using Homebrew
        script: |
          brew install cocoapods
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release archive -archivePath $HOME/build/Runner.xcarchive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $HOME/build/Runner.xcarchive -exportOptionsPlist ios/Runner/ExportOptions.plist -exportPath $HOME/build
    artifacts:
      - build/Runner.ipa
